# Generated by Django 5.1.4 on 2026-09-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100, verbose_name='Nombre del Pokemon')),
                ('Tipo', models.CharField(max_length=100, verbose_name='Tipo del Pokemon')),
                ('Descripcion', models.TextField(max_length=500, verbose_name='Descripción del Pokemon')),
                ('Imagen', models.ImageField(upload_to='images/', verbose_name='Imagen del Pokemon')),
            ],
            options={
                'verbose_name': 'Pokemon',
                'verbose_name_plural': 'Pokemons',
                'db_table': 'pokemon',
            },
        ),
    ]
