# Generated by Django 5.1.4 on 2026-09-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='NombreImagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de la imagen'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='Tipo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo del Pokemon'),
        ),
    ]
