# Generated by Django 5.1.4 on 2026-09-30 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pokemon', '0002_pokemon_nombreimagen_alter_pokemon_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='NombreImagen',
        ),
    ]
