# Generated by Django 5.1.4 on 2026-09-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pokemon', '0003_remove_pokemon_nombreimagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='Imagen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Imagen del Pokemon'),
        ),
    ]
